# ------------------------
# Minestore by abhi      #
# Version: 1.1           #
#-------------------------

# port
port: 33266
# password
password: "a nice password"

# Your shop Url (/shop command)
Url: "www.thisisashopurl.com/store"