# ------------------------
# Minestore by abhi      #
# Version: 1.1           #
#-------------------------

# port
port: 33266
# password
password: "a nice password"


# buy command enable (true or fales)
buy-enable: true


# url to send when /shop
Url: "www.thisisashopurl.com/store"

# Your shop api-url
Url-api: "mystore.com/api/top_donators"