main: com.abhiram.minestore.MineStore
name: MineStore
version: 2.1
Author: Abhiram
depend:
  - PlaceholderAPI
commands:
  buy:
    description: A buy GUI command
  ms:
    description: Plugin reload command
    usage: /ms <reload>
    permission: minestore.admin
